/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface EncryptedRatingSystemInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "allowUserToDecrypt"
      | "deleteRating"
      | "entryCount"
      | "getActiveEntryCount"
      | "getEncryptedGlobalStats"
      | "getEncryptedRating"
      | "getEncryptedSubjectStats"
      | "getEntry"
      | "getEntryCount"
      | "getGlobalStats"
      | "getSubjectEntryCount"
      | "getSubjectStats"
      | "globalStatsCallback"
      | "hasSubmitted"
      | "hasSubmittedForSubject"
      | "isGlobalStatsFinalized"
      | "isSubjectStatsFinalized"
      | "protocolId"
      | "ratingEntries"
      | "requestGlobalStats"
      | "requestSubjectStats"
      | "subjectStatsCallback"
      | "submitRating"
      | "updateRating"
      | "userSubjectEntryId"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "GlobalStatsPublished"
      | "GlobalStatsRequested"
      | "RatingDeleted"
      | "RatingSubmitted"
      | "RatingUpdated"
      | "SubjectStatsPublished"
      | "SubjectStatsRequested"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "allowUserToDecrypt",
    values: [AddressLike, string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "deleteRating",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "entryCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getActiveEntryCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedGlobalStats",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedRating",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedSubjectStats",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getEntry",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEntryCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getGlobalStats",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getSubjectEntryCount",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getSubjectStats",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "globalStatsCallback",
    values: [BigNumberish, BytesLike, BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "hasSubmitted",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasSubmittedForSubject",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "isGlobalStatsFinalized",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isSubjectStatsFinalized",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ratingEntries",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "requestGlobalStats",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestSubjectStats",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "subjectStatsCallback",
    values: [BigNumberish, BytesLike, BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "submitRating",
    values: [BytesLike, BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateRating",
    values: [BytesLike, BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "userSubjectEntryId",
    values: [AddressLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "allowUserToDecrypt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deleteRating",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "entryCount", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getActiveEntryCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedGlobalStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedRating",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedSubjectStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getEntry", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getEntryCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getGlobalStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSubjectEntryCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSubjectStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "globalStatsCallback",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasSubmitted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasSubmittedForSubject",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isGlobalStatsFinalized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isSubjectStatsFinalized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "ratingEntries",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestGlobalStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestSubjectStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "subjectStatsCallback",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitRating",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateRating",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userSubjectEntryId",
    data: BytesLike
  ): Result;
}

export namespace GlobalStatsPublishedEvent {
  export type InputTuple = [
    averageRating: BigNumberish,
    totalCount: BigNumberish
  ];
  export type OutputTuple = [averageRating: bigint, totalCount: bigint];
  export interface OutputObject {
    averageRating: bigint;
    totalCount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GlobalStatsRequestedEvent {
  export type InputTuple = [requestId: BigNumberish];
  export type OutputTuple = [requestId: bigint];
  export interface OutputObject {
    requestId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RatingDeletedEvent {
  export type InputTuple = [entryId: BigNumberish, submitter: AddressLike];
  export type OutputTuple = [entryId: bigint, submitter: string];
  export interface OutputObject {
    entryId: bigint;
    submitter: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RatingSubmittedEvent {
  export type InputTuple = [
    entryId: BigNumberish,
    submitter: AddressLike,
    subject: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    entryId: bigint,
    submitter: string,
    subject: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    entryId: bigint;
    submitter: string;
    subject: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RatingUpdatedEvent {
  export type InputTuple = [
    entryId: BigNumberish,
    submitter: AddressLike,
    newSubject: string
  ];
  export type OutputTuple = [
    entryId: bigint,
    submitter: string,
    newSubject: string
  ];
  export interface OutputObject {
    entryId: bigint;
    submitter: string;
    newSubject: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubjectStatsPublishedEvent {
  export type InputTuple = [
    subjectHash: BytesLike,
    averageRating: BigNumberish,
    count: BigNumberish
  ];
  export type OutputTuple = [
    subjectHash: string,
    averageRating: bigint,
    count: bigint
  ];
  export interface OutputObject {
    subjectHash: string;
    averageRating: bigint;
    count: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubjectStatsRequestedEvent {
  export type InputTuple = [subjectHash: BytesLike, requestId: BigNumberish];
  export type OutputTuple = [subjectHash: string, requestId: bigint];
  export interface OutputObject {
    subjectHash: string;
    requestId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EncryptedRatingSystem extends BaseContract {
  connect(runner?: ContractRunner | null): EncryptedRatingSystem;
  waitForDeployment(): Promise<this>;

  interface: EncryptedRatingSystemInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  allowUserToDecrypt: TypedContractMethod<
    [user: AddressLike, subjects: string[]],
    [void],
    "nonpayable"
  >;

  deleteRating: TypedContractMethod<[], [void], "nonpayable">;

  entryCount: TypedContractMethod<[], [bigint], "view">;

  getActiveEntryCount: TypedContractMethod<[], [bigint], "view">;

  getEncryptedGlobalStats: TypedContractMethod<
    [],
    [[string, bigint] & { encryptedSum: string; count: bigint }],
    "view"
  >;

  getEncryptedRating: TypedContractMethod<
    [entryId: BigNumberish],
    [string],
    "view"
  >;

  getEncryptedSubjectStats: TypedContractMethod<
    [subject: string],
    [[string, bigint] & { encryptedSum: string; count: bigint }],
    "view"
  >;

  getEntry: TypedContractMethod<
    [entryId: BigNumberish],
    [
      [string, bigint, string, boolean] & {
        subject: string;
        timestamp: bigint;
        submitter: string;
        isActive: boolean;
      }
    ],
    "view"
  >;

  getEntryCount: TypedContractMethod<[], [bigint], "view">;

  getGlobalStats: TypedContractMethod<
    [],
    [[bigint, bigint] & { averageRating: bigint; totalCount: bigint }],
    "view"
  >;

  getSubjectEntryCount: TypedContractMethod<
    [subject: string],
    [bigint],
    "view"
  >;

  getSubjectStats: TypedContractMethod<
    [subject: string],
    [[bigint, bigint] & { averageRating: bigint; count: bigint }],
    "view"
  >;

  globalStatsCallback: TypedContractMethod<
    [requestId: BigNumberish, cleartexts: BytesLike, arg2: BytesLike[]],
    [boolean],
    "nonpayable"
  >;

  hasSubmitted: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  hasSubmittedForSubject: TypedContractMethod<
    [user: AddressLike, subject: string],
    [boolean],
    "view"
  >;

  isGlobalStatsFinalized: TypedContractMethod<[], [boolean], "view">;

  isSubjectStatsFinalized: TypedContractMethod<
    [subject: string],
    [boolean],
    "view"
  >;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  ratingEntries: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, bigint, boolean] & {
        submitter: string;
        subject: string;
        encryptedRating: string;
        timestamp: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  requestGlobalStats: TypedContractMethod<[], [void], "nonpayable">;

  requestSubjectStats: TypedContractMethod<
    [subject: string],
    [void],
    "nonpayable"
  >;

  subjectStatsCallback: TypedContractMethod<
    [requestId: BigNumberish, cleartexts: BytesLike, arg2: BytesLike[]],
    [boolean],
    "nonpayable"
  >;

  submitRating: TypedContractMethod<
    [encryptedRating: BytesLike, inputProof: BytesLike, subject: string],
    [void],
    "nonpayable"
  >;

  updateRating: TypedContractMethod<
    [encryptedRating: BytesLike, inputProof: BytesLike, newSubject: string],
    [void],
    "nonpayable"
  >;

  userSubjectEntryId: TypedContractMethod<
    [arg0: AddressLike, arg1: BytesLike],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "allowUserToDecrypt"
  ): TypedContractMethod<
    [user: AddressLike, subjects: string[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deleteRating"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "entryCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getActiveEntryCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getEncryptedGlobalStats"
  ): TypedContractMethod<
    [],
    [[string, bigint] & { encryptedSum: string; count: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEncryptedRating"
  ): TypedContractMethod<[entryId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getEncryptedSubjectStats"
  ): TypedContractMethod<
    [subject: string],
    [[string, bigint] & { encryptedSum: string; count: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEntry"
  ): TypedContractMethod<
    [entryId: BigNumberish],
    [
      [string, bigint, string, boolean] & {
        subject: string;
        timestamp: bigint;
        submitter: string;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEntryCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getGlobalStats"
  ): TypedContractMethod<
    [],
    [[bigint, bigint] & { averageRating: bigint; totalCount: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSubjectEntryCount"
  ): TypedContractMethod<[subject: string], [bigint], "view">;
  getFunction(
    nameOrSignature: "getSubjectStats"
  ): TypedContractMethod<
    [subject: string],
    [[bigint, bigint] & { averageRating: bigint; count: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "globalStatsCallback"
  ): TypedContractMethod<
    [requestId: BigNumberish, cleartexts: BytesLike, arg2: BytesLike[]],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasSubmitted"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "hasSubmittedForSubject"
  ): TypedContractMethod<
    [user: AddressLike, subject: string],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isGlobalStatsFinalized"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "isSubjectStatsFinalized"
  ): TypedContractMethod<[subject: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "ratingEntries"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, bigint, boolean] & {
        submitter: string;
        subject: string;
        encryptedRating: string;
        timestamp: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "requestGlobalStats"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requestSubjectStats"
  ): TypedContractMethod<[subject: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "subjectStatsCallback"
  ): TypedContractMethod<
    [requestId: BigNumberish, cleartexts: BytesLike, arg2: BytesLike[]],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitRating"
  ): TypedContractMethod<
    [encryptedRating: BytesLike, inputProof: BytesLike, subject: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateRating"
  ): TypedContractMethod<
    [encryptedRating: BytesLike, inputProof: BytesLike, newSubject: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "userSubjectEntryId"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BytesLike],
    [bigint],
    "view"
  >;

  getEvent(
    key: "GlobalStatsPublished"
  ): TypedContractEvent<
    GlobalStatsPublishedEvent.InputTuple,
    GlobalStatsPublishedEvent.OutputTuple,
    GlobalStatsPublishedEvent.OutputObject
  >;
  getEvent(
    key: "GlobalStatsRequested"
  ): TypedContractEvent<
    GlobalStatsRequestedEvent.InputTuple,
    GlobalStatsRequestedEvent.OutputTuple,
    GlobalStatsRequestedEvent.OutputObject
  >;
  getEvent(
    key: "RatingDeleted"
  ): TypedContractEvent<
    RatingDeletedEvent.InputTuple,
    RatingDeletedEvent.OutputTuple,
    RatingDeletedEvent.OutputObject
  >;
  getEvent(
    key: "RatingSubmitted"
  ): TypedContractEvent<
    RatingSubmittedEvent.InputTuple,
    RatingSubmittedEvent.OutputTuple,
    RatingSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "RatingUpdated"
  ): TypedContractEvent<
    RatingUpdatedEvent.InputTuple,
    RatingUpdatedEvent.OutputTuple,
    RatingUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "SubjectStatsPublished"
  ): TypedContractEvent<
    SubjectStatsPublishedEvent.InputTuple,
    SubjectStatsPublishedEvent.OutputTuple,
    SubjectStatsPublishedEvent.OutputObject
  >;
  getEvent(
    key: "SubjectStatsRequested"
  ): TypedContractEvent<
    SubjectStatsRequestedEvent.InputTuple,
    SubjectStatsRequestedEvent.OutputTuple,
    SubjectStatsRequestedEvent.OutputObject
  >;

  filters: {
    "GlobalStatsPublished(uint32,uint32)": TypedContractEvent<
      GlobalStatsPublishedEvent.InputTuple,
      GlobalStatsPublishedEvent.OutputTuple,
      GlobalStatsPublishedEvent.OutputObject
    >;
    GlobalStatsPublished: TypedContractEvent<
      GlobalStatsPublishedEvent.InputTuple,
      GlobalStatsPublishedEvent.OutputTuple,
      GlobalStatsPublishedEvent.OutputObject
    >;

    "GlobalStatsRequested(uint256)": TypedContractEvent<
      GlobalStatsRequestedEvent.InputTuple,
      GlobalStatsRequestedEvent.OutputTuple,
      GlobalStatsRequestedEvent.OutputObject
    >;
    GlobalStatsRequested: TypedContractEvent<
      GlobalStatsRequestedEvent.InputTuple,
      GlobalStatsRequestedEvent.OutputTuple,
      GlobalStatsRequestedEvent.OutputObject
    >;

    "RatingDeleted(uint256,address)": TypedContractEvent<
      RatingDeletedEvent.InputTuple,
      RatingDeletedEvent.OutputTuple,
      RatingDeletedEvent.OutputObject
    >;
    RatingDeleted: TypedContractEvent<
      RatingDeletedEvent.InputTuple,
      RatingDeletedEvent.OutputTuple,
      RatingDeletedEvent.OutputObject
    >;

    "RatingSubmitted(uint256,address,string,uint256)": TypedContractEvent<
      RatingSubmittedEvent.InputTuple,
      RatingSubmittedEvent.OutputTuple,
      RatingSubmittedEvent.OutputObject
    >;
    RatingSubmitted: TypedContractEvent<
      RatingSubmittedEvent.InputTuple,
      RatingSubmittedEvent.OutputTuple,
      RatingSubmittedEvent.OutputObject
    >;

    "RatingUpdated(uint256,address,string)": TypedContractEvent<
      RatingUpdatedEvent.InputTuple,
      RatingUpdatedEvent.OutputTuple,
      RatingUpdatedEvent.OutputObject
    >;
    RatingUpdated: TypedContractEvent<
      RatingUpdatedEvent.InputTuple,
      RatingUpdatedEvent.OutputTuple,
      RatingUpdatedEvent.OutputObject
    >;

    "SubjectStatsPublished(bytes32,uint32,uint32)": TypedContractEvent<
      SubjectStatsPublishedEvent.InputTuple,
      SubjectStatsPublishedEvent.OutputTuple,
      SubjectStatsPublishedEvent.OutputObject
    >;
    SubjectStatsPublished: TypedContractEvent<
      SubjectStatsPublishedEvent.InputTuple,
      SubjectStatsPublishedEvent.OutputTuple,
      SubjectStatsPublishedEvent.OutputObject
    >;

    "SubjectStatsRequested(bytes32,uint256)": TypedContractEvent<
      SubjectStatsRequestedEvent.InputTuple,
      SubjectStatsRequestedEvent.OutputTuple,
      SubjectStatsRequestedEvent.OutputObject
    >;
    SubjectStatsRequested: TypedContractEvent<
      SubjectStatsRequestedEvent.InputTuple,
      SubjectStatsRequestedEvent.OutputTuple,
      SubjectStatsRequestedEvent.OutputObject
    >;
  };
}
